### GET /
GET http://localhost:5000

### Register User /AUTH/REGISTER
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "testuser@gmail.com",
  "password": "testpassword"
}

### login user to /AUTH/LOGIN 
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "username": "testuser@gmail.com",
  "password": "testpassword"
}


###


###
